"""Add soft delete and token version to users

Revision ID: e8574fc4308a
Revises: 4addab7eb67c
Create Date: 2026-05-24 20:21:24.971139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8574fc4308a'
down_revision: Union[str, Sequence[str], None] = '4addab7eb67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        batch_op.drop_column('physical_address')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('scheduled_purge_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('scheduled_purge_at')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physical_address', sa.VARCHAR(length=512), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
