"""enterprise_hospital_verification

Revision ID: 2fe6f99be20f
Revises: e8574fc4308a
Create Date: 2026-05-27 11:52:39.162963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2fe6f99be20f'
down_revision: Union[str, Sequence[str], None] = 'e8574fc4308a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('sms_notifications_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('session_timeout_minutes', sa.Integer(), server_default=sa.text('15'), nullable=False))

    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        # batch_op.drop_column('physical_address')
        pass

    # Explicitly create the ENUM type for PostgreSQL
    hospital_status_enum = postgresql.ENUM('draft', 'submitted', 'under_review', 'request_more_info', 'verified', 'rejected', 'suspended', 'blacklisted', 'verification_expired', name='hospitalverificationstatusenum')
    hospital_status_enum.create(op.get_bind(), checkfirst=True)

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hospital_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('domain', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gst_number', sa.String(length=100), nullable=True))
        # Adding the enum column and using server_default to ensure existing rows don't break the NOT NULL constraint
        batch_op.add_column(sa.Column('status', hospital_status_enum, nullable=False, server_default='draft'))
        batch_op.add_column(sa.Column('risk_score', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('trust_score', sa.Integer(), nullable=False, server_default='100'))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('blacklisted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_hospitals_domain'), ['domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_hospitals_gst_number'), ['gst_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_hospitals_hospital_email'), ['hospital_email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_hospital_email'))
        batch_op.drop_index(batch_op.f('ix_hospitals_gst_number'))
        batch_op.drop_index(batch_op.f('ix_hospitals_domain'))
        batch_op.drop_column('blacklisted_at')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('trust_score')
        batch_op.drop_column('risk_score')
        batch_op.drop_column('status')
        batch_op.drop_column('gst_number')
        batch_op.drop_column('domain')
        batch_op.drop_column('hospital_phone')
        batch_op.drop_column('hospital_email')

    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('physical_address', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        pass

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.alter_column('session_timeout_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('15'))
        batch_op.alter_column('sms_notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('email_notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    # Drop the ENUM type
    hospital_status_enum = postgresql.ENUM('draft', 'submitted', 'under_review', 'request_more_info', 'verified', 'rejected', 'suspended', 'blacklisted', 'verification_expired', name='hospitalverificationstatusenum')
    hospital_status_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
