"""Add OP Fee, Staff Status, and Photo URL

Revision ID: 3a331b4201ae
Revises: a6634c22f620
Create Date: 2026-05-24 00:06:24.919524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a331b4201ae'
down_revision: Union[str, Sequence[str], None] = 'a6634c22f620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        # batch_op.drop_column('physical_address')
        pass

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('hospitals_qr_code_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_hospitals_qr_code_id'), ['qr_code_id'], unique=True)

    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('op_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('op_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_photo_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_photo_url')
        batch_op.drop_column('current_status')

    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('op_fee')

    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('op_fee')

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_qr_code_id'))
        batch_op.create_unique_constraint(batch_op.f('hospitals_qr_code_id_key'), ['qr_code_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('physical_address', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        pass

    # ### end Alembic commands ###
