"""Add notifications and privacy to hospital_settings

Revision ID: 4addab7eb67c
Revises: 3a331b4201ae
Create Date: 2026-05-24 10:10:32.825768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4addab7eb67c'
down_revision: Union[str, Sequence[str], None] = '3a331b4201ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        # batch_op.drop_column('physical_address')
        pass

    with op.batch_alter_table('hospital_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sms_notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('whatsapp_notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.add_column(sa.Column('require_patient_consent', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('data_sharing_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_settings', schema=None) as batch_op:
        batch_op.drop_column('data_sharing_enabled')
        batch_op.drop_column('require_patient_consent')
        batch_op.drop_column('whatsapp_notifications_enabled')
        batch_op.drop_column('email_notifications_enabled')
        batch_op.drop_column('sms_notifications_enabled')

    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('physical_address', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
        pass

    # ### end Alembic commands ###
