"""Add HospitalSettings

Revision ID: 63853fc5832c
Revises: b030bfb36dbd
Create Date: 2026-05-20 10:42:12.302582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63853fc5832c'
down_revision: Union[str, Sequence[str], None] = 'b030bfb36dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('enable_pharmacy', sa.Boolean(), nullable=False),
    sa.Column('enable_labs', sa.Boolean(), nullable=False),
    sa.Column('enable_inpatient_beds', sa.Boolean(), nullable=False),
    sa.Column('enable_hr', sa.Boolean(), nullable=False),
    sa.Column('enable_billing', sa.Boolean(), nullable=False),
    sa.Column('max_beds_configured', sa.Integer(), nullable=False),
    sa.Column('has_multiple_branches', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_settings_hospital_id'), ['hospital_id'], unique=True)

    with op.batch_alter_table('forensic_verification_logs', schema=None) as batch_op:
        batch_op.alter_column('pan_otp_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        batch_op.drop_column('physical_address')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physical_address', sa.VARCHAR(length=512), autoincrement=False, nullable=True))

    with op.batch_alter_table('forensic_verification_logs', schema=None) as batch_op:
        batch_op.alter_column('pan_otp_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('hospital_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_settings_hospital_id'))

    op.drop_table('hospital_settings')
    # ### end Alembic commands ###
