"""Add partner referral models

Revision ID: 7cf822e8a836
Revises: 63853fc5832c
Create Date: 2026-05-20 12:53:20.729593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf822e8a836'
down_revision: Union[str, Sequence[str], None] = '63853fc5832c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_pharmacy_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prescription_id', sa.Uuid(), nullable=False),
    sa.Column('referring_hospital_id', sa.UUID(), nullable=False),
    sa.Column('partner_pharmacy_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'fulfilled', 'rejected', name='partnerreferralstatusenum'), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['partner_pharmacy_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['digital_prescriptions.id'], ),
    sa.ForeignKeyConstraint(['referring_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_pharmacy_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_pharmacy_requests_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_pharmacy_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_pharmacy_requests_partner_pharmacy_id'), ['partner_pharmacy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_pharmacy_requests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_pharmacy_requests_prescription_id'), ['prescription_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_pharmacy_requests_referring_hospital_id'), ['referring_hospital_id'], unique=False)

    op.create_table('partner_lab_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('referring_hospital_id', sa.UUID(), nullable=False),
    sa.Column('partner_hospital_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'fulfilled', 'rejected', name='partnerreferralstatusenum'), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['lab_diagnostic_orders.id'], ),
    sa.ForeignKeyConstraint(['partner_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['referring_hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_lab_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_lab_requests_hospital_id'), ['hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_lab_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_lab_requests_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_lab_requests_partner_hospital_id'), ['partner_hospital_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_lab_requests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_lab_requests_referring_hospital_id'), ['referring_hospital_id'], unique=False)

    with op.batch_alter_table('digital_prescriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_member_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_digital_prescriptions_family_member_id'), ['family_member_id'], unique=False)
        batch_op.create_foreign_key(None, 'family_members', ['family_member_id'], ['id'])

    with op.batch_alter_table('lab_diagnostic_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_member_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lab_diagnostic_orders_family_member_id'), ['family_member_id'], unique=False)
        batch_op.create_foreign_key(None, 'family_members', ['family_member_id'], ['id'])

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'patient_visits', ['visit_id'], ['id'])

    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_member_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patient_visits_family_member_id'), ['family_member_id'], unique=False)
        batch_op.create_foreign_key(None, 'family_members', ['family_member_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_visits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patient_visits_family_member_id'))
        batch_op.drop_column('family_member_id')

    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visit_id')

    with op.batch_alter_table('lab_diagnostic_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lab_diagnostic_orders_family_member_id'))
        batch_op.drop_column('family_member_id')

    with op.batch_alter_table('digital_prescriptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_digital_prescriptions_family_member_id'))
        batch_op.drop_column('family_member_id')

    with op.batch_alter_table('partner_lab_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_lab_requests_referring_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_partner_lab_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_partner_lab_requests_partner_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_partner_lab_requests_order_id'))
        batch_op.drop_index(batch_op.f('ix_partner_lab_requests_id'))
        batch_op.drop_index(batch_op.f('ix_partner_lab_requests_hospital_id'))

    op.drop_table('partner_lab_requests')
    with op.batch_alter_table('partner_pharmacy_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_pharmacy_requests_referring_hospital_id'))
        batch_op.drop_index(batch_op.f('ix_partner_pharmacy_requests_prescription_id'))
        batch_op.drop_index(batch_op.f('ix_partner_pharmacy_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_partner_pharmacy_requests_partner_pharmacy_id'))
        batch_op.drop_index(batch_op.f('ix_partner_pharmacy_requests_id'))
        batch_op.drop_index(batch_op.f('ix_partner_pharmacy_requests_hospital_id'))

    op.drop_table('partner_pharmacy_requests')
    # ### end Alembic commands ###
