"""add_branches_and_subscriptions

Revision ID: a2985dd1c6fa
Revises: 91ef92a2d141
Create Date: 2026-05-19 12:29:37.282043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2985dd1c6fa'
down_revision: Union[str, Sequence[str], None] = '91ef92a2d141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('auto_debit_token', sa.String(length=255), nullable=True),
    sa.Column('trial_starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id')
    )
    op.create_table('hospital_branches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hospital_branches_hospital_id'), ['hospital_id'], unique=False)

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pan_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('selfie_url', sa.String(length=512), nullable=True))

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('family_member_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('observation_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('order_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_lab_results_family_member_id'), ['family_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_record_id'), ['record_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('lab_results_hospital_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'family_members', ['family_member_id'], ['id'])
        batch_op.create_foreign_key(None, 'medical_records', ['record_id'], ['id'])

    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'hospital_branches', ['branch_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['phone_number'], unique=True)

    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_id')

    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('lab_results_hospital_id_fkey'), 'hospitals', ['hospital_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_index(batch_op.f('ix_lab_results_record_id'))
        batch_op.drop_index(batch_op.f('ix_lab_results_family_member_id'))
        batch_op.alter_column('order_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('observation_date')
        batch_op.drop_column('family_member_id')
        batch_op.drop_column('record_id')

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_column('selfie_url')
        batch_op.drop_column('pan_number')

    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospital_branches_hospital_id'))

    op.drop_table('hospital_branches')
    op.drop_table('billing_subscriptions')
    # ### end Alembic commands ###
