"""Add qr_code_id to hospitals

Revision ID: a6634c22f620
Revises: 0f470e240a8b
Create Date: 2026-05-23 12:33:06.015212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a6634c22f620'
down_revision: Union[str, Sequence[str], None] = '0f470e240a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    verification_type_enum = postgresql.ENUM('drug_license', 'medical_degree', 'hospital_registration', 'identity_proof', name='verificationtypeenum')
    verification_type_enum.create(op.get_bind())
    
    op.create_table('verification_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospyn_id', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('document_type', postgresql.ENUM('drug_license', 'medical_degree', 'hospital_registration', 'identity_proof', name='verificationtypeenum', create_type=False), nullable=False),
    sa.Column('document_url', sa.String(length=512), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('biometric_hash', sa.String(length=255), nullable=True),
    sa.Column('identity_photo_url', sa.String(length=512), nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'ai_processing', 'flagged', 'verified', 'rejected', name='verificationstatusenum', create_type=False), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('ai_notes', sa.String(length=1000), nullable=True),
    sa.Column('audited_by', sa.Uuid(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_requests_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_requests_hospyn_id'), ['hospyn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_requests_license_number'), ['license_number'], unique=False)

    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        batch_op.drop_column('physical_address')

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_hospitals_qr_code_id'), ['qr_code_id'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_temporary_password',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_temporary_password',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hospitals_qr_code_id'))
        batch_op.drop_column('qr_code_id')

    with op.batch_alter_table('hospital_branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('physical_address', sa.VARCHAR(length=512), autoincrement=False, nullable=True))

    with op.batch_alter_table('verification_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_requests_license_number'))
        batch_op.drop_index(batch_op.f('ix_verification_requests_hospyn_id'))
        batch_op.drop_index(batch_op.f('ix_verification_requests_entity_id'))

    op.drop_table('verification_requests')
    # ### end Alembic commands ###
