"""add_upi_and_forensic_logs

Revision ID: b030bfb36dbd
Revises: a2985dd1c6fa
Create Date: 2026-05-19 13:22:27.532247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b030bfb36dbd'
down_revision: Union[str, Sequence[str], None] = 'a2985dd1c6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forensic_verification_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hospital_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('phone_otp_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_otp_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pan_number', sa.String(length=50), nullable=False),
    sa.Column('pan_matched_name', sa.String(length=255), nullable=True),
    sa.Column('is_pan_valid', sa.Boolean(), nullable=False),
    sa.Column('pan_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certificate_url', sa.String(length=512), nullable=False),
    sa.Column('is_certificate_valid', sa.Boolean(), nullable=False),
    sa.Column('cert_extracted_reg_no', sa.String(length=100), nullable=True),
    sa.Column('cert_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forensic_verification_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forensic_verification_logs_hospital_id'), ['hospital_id'], unique=False)

    with op.batch_alter_table('billing_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upi_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_method_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('payment_method_type')
        batch_op.drop_column('upi_id')

    with op.batch_alter_table('forensic_verification_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forensic_verification_logs_hospital_id'))

    op.drop_table('forensic_verification_logs')
    # ### end Alembic commands ###
