"""
backend/auth-service/app/models/user.py

CHANGES (Employee ID Login Overhaul):
  - Added employee_id field: 6-char unique ID, always contains H and R,
    mixed letters+digits. Format example: H3Rk9T, 2RHm4X etc.
  - Added is_temporary_password: flag to force password change on first login
  - Added force_password_change: alias/clarifier flag
  - RoleEnum extended with hospain_employee roles

Previous fixes retained:
  FIX-U1: Added missing roles
  FIX-U2: Added full_name field
  FIX-U3: phone_verified, auth_provider, has_usable_password
"""

import uuid
import enum
from datetime import datetime
from sqlalchemy import String, Integer, DateTime, Enum as SQLEnum, UUID, func, Boolean
from sqlalchemy.orm import Mapped, mapped_column
from shared.database.core import Base


class RoleEnum(str, enum.Enum):
    patient        = "patient"
    doctor         = "doctor"
    admin          = "admin"
    hospital_admin = "hospital_admin"
    staff          = "staff"
    nurse          = "nurse"
    pharmacist     = "pharmacist"
    super_admin    = "super_admin"
    owner          = "owner"
    receptionist   = "receptionist"
    lab            = "lab"
    hr             = "hr"
    # Hospain internal employee roles
    manager        = "manager"
    team_lead      = "team_lead"
    l1             = "l1"
    l2             = "l2"
    support        = "support"
    finance        = "finance"
    engineering    = "engineering"
    onboarding     = "onboarding"
    data           = "data"
    verification   = "verification"
    employee       = "employee"


class User(Base):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True
    )
    full_name: Mapped[str] = mapped_column(String(255), nullable=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True, nullable=True)
    phone_number: Mapped[str] = mapped_column(
        String(20), unique=True, index=True, nullable=True
    )
    hashed_password: Mapped[str] = mapped_column(String(255))
    role: Mapped[RoleEnum] = mapped_column(SQLEnum(RoleEnum), default=RoleEnum.patient)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    token_version: Mapped[int] = mapped_column(Integer, default=1)

    # Employee ID: 6-char unique identifier always containing H and R
    # e.g. H3Rk9T, 2RHm4X, 7HkR2N
    # Generated by generate_employee_id() in auth_service.py
    employee_id: Mapped[str] = mapped_column(
        String(10), unique=True, index=True, nullable=True
    )

    # First-login force password change flag
    # Set to True when admin creates employee with temp password
    # Cleared to False after employee sets their own password
    is_temporary_password: Mapped[bool] = mapped_column(Boolean, default=False)

    phone_verified: Mapped[bool] = mapped_column(Boolean, default=False)
    auth_provider: Mapped[str] = mapped_column(String(20), default="local")
    has_usable_password: Mapped[bool] = mapped_column(Boolean, default=True)
    hospital_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=True, index=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
    deleted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)


class OTPVerification(Base):
    __tablename__ = "otp_verifications"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True
    )
    identifier: Mapped[str] = mapped_column(String(255), index=True)
    hashed_otp: Mapped[str] = mapped_column(String(255))
    attempts: Mapped[int] = mapped_column(Integer, default=0)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    is_verified: Mapped[bool] = mapped_column(Boolean, default=False)


class PasswordResetToken(Base):
    __tablename__ = "password_reset_tokens"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    hashed_token: Mapped[str] = mapped_column(String(255), nullable=False)
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    is_used: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
